# Generated by Django 4.2.15 on 2024-08-27 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courseimage',
            name='image',
            field=models.ImageField(default=1, upload_to='course/images'),
            preserve_default=False,
        ),
    ]
