# Generated by Django 4.2.15 on 2024-08-27 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_customer_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='course/images'),
        ),
    ]
