# Generated by Django 4.2.15 on 2024-09-02 15:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_review_user_review_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseprogress',
            name='progress',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
    ]
