# Generated by Django 4.2.15 on 2024-09-06 13:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_courseprogress_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseimage',
            name='video',
        ),
        migrations.AlterField(
            model_name='courseimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='course/images', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png'])]),
        ),
        migrations.CreateModel(
            name='CourseVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='course/videos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'pdf'])])),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='courses.course')),
            ],
            options={
                'unique_together': {('video',)},
            },
        ),
    ]
