# Generated by Django 4.2.15 on 2024-10-04 19:16

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default=datetime.datetime.now, upload_to='course/images', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png'])]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='ratingCount',
            field=models.PositiveIntegerField(blank=True, default='0'),
        ),
    ]
