# Generated by Django 4.2.15 on 2024-10-11 13:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseprogress',
            unique_together={('student', 'course', 'lesson')},
        ),
    ]
