# Generated by Django 4.2.15 on 2024-10-28 13:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='duration',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='file',
            field=models.FileField(blank=True, null=True, unique=True, upload_to='course/lessons/files', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'wmv', 'mkv', 'flv', 'mpeg', 'doc', 'docx', 'pdf', 'txt', 'rtf', 'odt', 'html', 'htm'])]),
        ),
    ]
