# Generated by Django 4.2.15 on 2024-09-19 20:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_currency'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coursevideo',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='coursevideo',
            name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='course/images', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png'])]),
        ),
        migrations.AddField(
            model_name='course',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='course/videos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'pdf'])]),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('video',)},
        ),
        migrations.DeleteModel(
            name='CourseImage',
        ),
        migrations.DeleteModel(
            name='CourseVideo',
        ),
    ]
