# Generated by Django 4.2.15 on 2024-10-12 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_courseprogress_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='file',
            new_name='preview',
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('preview',)},
        ),
    ]
