# Generated by Django 4.2.15 on 2024-10-28 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_lesson_duration_alter_lesson_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='duration',
        ),
        migrations.AddField(
            model_name='section',
            name='total_duration',
            field=models.DurationField(blank=True, default=datetime.timedelta),
        ),
    ]
