# Generated by Django 4.2.15 on 2024-10-28 20:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_section_duration_section_total_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='duration',
        ),
        migrations.AddField(
            model_name='course',
            name='total_duration',
            field=models.DurationField(blank=True, default=datetime.timedelta),
        ),
    ]
