# Generated by Django 4.2.15 on 2024-10-12 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='numberOfStudents',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
