# Generated by Django 4.2.15 on 2024-10-13 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_lesson_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='numberOfStudents',
        ),
    ]
