# Generated by Django 4.2.15 on 2024-10-13 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_remove_course_numberofstudents'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='numberOfStudents',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
