# Generated by Django 4.2.15 on 2024-10-16 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_alter_course_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='objectives',
            field=models.TextField(),
        ),
    ]
