# Generated by Django 4.2.15 on 2024-10-18 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_remove_course_rating_alter_course_ratingcount_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='course',
        ),
    ]
