# Generated by Django 4.2.15 on 2024-10-19 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_alter_rating_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='course',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
            preserve_default=False,
        ),
    ]
