# Generated by Django 4.2.15 on 2024-10-19 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_rating_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='opened',
            field=models.BooleanField(default=False),
        ),
    ]
